/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_RRC_UE_ADD_PB_H_INCLUDED
#define PB_RRC_UE_ADD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _rrc_ue_add {
    uint64_t timestamp;
    uint32_t cucp_ue_index;
    uint32_t c_rnti;
    uint32_t pci;
    uint32_t tac;
    uint32_t plmn;
    uint64_t nci;
} rrc_ue_add;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define rrc_ue_add_init_default                  {0, 0, 0, 0, 0, 0, 0}
#define rrc_ue_add_init_zero                     {0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define rrc_ue_add_timestamp_tag                 1
#define rrc_ue_add_cucp_ue_index_tag             2
#define rrc_ue_add_c_rnti_tag                    3
#define rrc_ue_add_pci_tag                       4
#define rrc_ue_add_tac_tag                       5
#define rrc_ue_add_plmn_tag                      6
#define rrc_ue_add_nci_tag                       7

/* Struct field encoding specification for nanopb */
#define rrc_ue_add_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT32,   cucp_ue_index,     2) \
X(a, STATIC,   REQUIRED, UINT32,   c_rnti,            3) \
X(a, STATIC,   REQUIRED, UINT32,   pci,               4) \
X(a, STATIC,   REQUIRED, UINT32,   tac,               5) \
X(a, STATIC,   REQUIRED, UINT32,   plmn,              6) \
X(a, STATIC,   REQUIRED, UINT64,   nci,               7)
#define rrc_ue_add_CALLBACK NULL
#define rrc_ue_add_DEFAULT NULL

extern const pb_msgdesc_t rrc_ue_add_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rrc_ue_add_fields &rrc_ue_add_msg

/* Maximum encoded size of messages (where known) */
#define RRC_UE_ADD_PB_H_MAX_SIZE                 rrc_ue_add_size
#define rrc_ue_add_size                          52

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
