/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_RRC_UE_UPDATE_ID_PB_H_INCLUDED
#define PB_RRC_UE_UPDATE_ID_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _rrc_ue_update_id {
    uint64_t timestamp;
    uint32_t cucp_ue_index;
    uint32_t tmsi;
} rrc_ue_update_id;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define rrc_ue_update_id_init_default            {0, 0, 0}
#define rrc_ue_update_id_init_zero               {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define rrc_ue_update_id_timestamp_tag           1
#define rrc_ue_update_id_cucp_ue_index_tag       2
#define rrc_ue_update_id_tmsi_tag                3

/* Struct field encoding specification for nanopb */
#define rrc_ue_update_id_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT32,   cucp_ue_index,     2) \
X(a, STATIC,   REQUIRED, UINT32,   tmsi,              3)
#define rrc_ue_update_id_CALLBACK NULL
#define rrc_ue_update_id_DEFAULT NULL

extern const pb_msgdesc_t rrc_ue_update_id_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rrc_ue_update_id_fields &rrc_ue_update_id_msg

/* Maximum encoded size of messages (where known) */
#define RRC_UE_UPDATE_ID_PB_H_MAX_SIZE           rrc_ue_update_id_size
#define rrc_ue_update_id_size                    23

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
