/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_RRC_UE_UPDATE_CONTEXT_PB_H_INCLUDED
#define PB_RRC_UE_UPDATE_CONTEXT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _rrc_ue_update_context {
    uint64_t timestamp;
    uint32_t cucp_ue_index;
    uint32_t old_cucp_ue_index;
    uint32_t c_rnti;
    uint32_t pci;
    uint32_t tac;
    uint32_t plmn;
    uint64_t nci;
} rrc_ue_update_context;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define rrc_ue_update_context_init_default       {0, 0, 0, 0, 0, 0, 0, 0}
#define rrc_ue_update_context_init_zero          {0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define rrc_ue_update_context_timestamp_tag      1
#define rrc_ue_update_context_cucp_ue_index_tag  2
#define rrc_ue_update_context_old_cucp_ue_index_tag 3
#define rrc_ue_update_context_c_rnti_tag         4
#define rrc_ue_update_context_pci_tag            5
#define rrc_ue_update_context_tac_tag            6
#define rrc_ue_update_context_plmn_tag           7
#define rrc_ue_update_context_nci_tag            8

/* Struct field encoding specification for nanopb */
#define rrc_ue_update_context_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT32,   cucp_ue_index,     2) \
X(a, STATIC,   REQUIRED, UINT32,   old_cucp_ue_index,   3) \
X(a, STATIC,   REQUIRED, UINT32,   c_rnti,            4) \
X(a, STATIC,   REQUIRED, UINT32,   pci,               5) \
X(a, STATIC,   REQUIRED, UINT32,   tac,               6) \
X(a, STATIC,   REQUIRED, UINT32,   plmn,              7) \
X(a, STATIC,   REQUIRED, UINT64,   nci,               8)
#define rrc_ue_update_context_CALLBACK NULL
#define rrc_ue_update_context_DEFAULT NULL

extern const pb_msgdesc_t rrc_ue_update_context_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rrc_ue_update_context_fields &rrc_ue_update_context_msg

/* Maximum encoded size of messages (where known) */
#define RRC_UE_UPDATE_CONTEXT_PB_H_MAX_SIZE      rrc_ue_update_context_size
#define rrc_ue_update_context_size               58

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
