/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_RRC_UE_PROCEDURE_PB_H_INCLUDED
#define PB_RRC_UE_PROCEDURE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _rrc_ue_procedure {
    uint64_t timestamp;
    uint32_t cucp_ue_index;
    uint32_t procedure;
    uint32_t success;
    uint32_t meta;
} rrc_ue_procedure;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define rrc_ue_procedure_init_default            {0, 0, 0, 0, 0}
#define rrc_ue_procedure_init_zero               {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define rrc_ue_procedure_timestamp_tag           1
#define rrc_ue_procedure_cucp_ue_index_tag       2
#define rrc_ue_procedure_procedure_tag           3
#define rrc_ue_procedure_success_tag             4
#define rrc_ue_procedure_meta_tag                5

/* Struct field encoding specification for nanopb */
#define rrc_ue_procedure_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT32,   cucp_ue_index,     2) \
X(a, STATIC,   REQUIRED, UINT32,   procedure,         3) \
X(a, STATIC,   REQUIRED, UINT32,   success,           4) \
X(a, STATIC,   REQUIRED, UINT32,   meta,              5)
#define rrc_ue_procedure_CALLBACK NULL
#define rrc_ue_procedure_DEFAULT NULL

extern const pb_msgdesc_t rrc_ue_procedure_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rrc_ue_procedure_fields &rrc_ue_procedure_msg

/* Maximum encoded size of messages (where known) */
#define RRC_UE_PROCEDURE_PB_H_MAX_SIZE           rrc_ue_procedure_size
#define rrc_ue_procedure_size                    35

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
