apiVersion: 1

datasources:
  - name: srsRAN InfluxDB
    type: influxdb
    uid: srsran_influxdb
    access: proxy
    url: http://localhost:8086
    database: srsran_telemetry
    isDefault: true
    editable: true
    jsonData:
      httpMode: GET
      timeInterval: "1s"
