/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_UE_CONTEXTS_PB_H_INCLUDED
#define PB_UE_CONTEXTS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _du_ue_ctx_creation {
    uint64_t timestamp;
    uint32_t du_ue_index;
    uint32_t tac;
    uint32_t plmn;
    uint32_t nci;
    uint32_t pci;
    uint32_t crnti;
} du_ue_ctx_creation;

typedef struct _du_ue_ctx_update_crnti {
    uint64_t timestamp;
    uint32_t du_ue_index;
    uint32_t crnti;
} du_ue_ctx_update_crnti;

typedef struct _du_ue_ctx_deletion {
    uint64_t timestamp;
    uint32_t du_ue_index;
} du_ue_ctx_deletion;

typedef struct _cucp_ue_ctx_creation {
    uint64_t timestamp;
    uint32_t cucp_ue_index;
    uint32_t plmn;
    bool has_pci;
    uint32_t pci;
    bool has_crnti;
    uint32_t crnti;
} cucp_ue_ctx_creation;

typedef struct _cucp_ue_ctx_update {
    uint64_t timestamp;
    uint32_t cucp_ue_index;
    uint32_t plmn;
    uint32_t pci;
    uint32_t crnti;
} cucp_ue_ctx_update;

typedef struct _cucp_ue_ctx_deletion {
    uint64_t timestamp;
    uint32_t cucp_ue_index;
} cucp_ue_ctx_deletion;

typedef struct _e1ap_cucp_bearer_ctx_setup {
    uint64_t timestamp;
    uint32_t cucp_ue_index;
    uint32_t cucp_ue_e1ap_id;
} e1ap_cucp_bearer_ctx_setup;

typedef struct _e1ap_cuup_bearer_ctx_setup {
    uint64_t timestamp;
    uint32_t cuup_ue_index;
    bool success;
    uint32_t cucp_ue_e1ap_id;
    uint32_t cuup_ue_e1ap_id;
} e1ap_cuup_bearer_ctx_setup;

typedef struct _e1ap_cuup_bearer_ctx_release {
    uint64_t timestamp;
    uint32_t cuup_ue_index;
    bool success;
    uint32_t cucp_ue_e1ap_id;
    uint32_t cuup_ue_e1ap_id;
} e1ap_cuup_bearer_ctx_release;

typedef struct _nssai_t {
    uint32_t sst;
    uint32_t sd;
} nssai_t;

typedef struct _cucp_pdu_session_bearer_add_modify {
    uint64_t timestamp;
    uint64_t cucp_ue_index;
    uint32_t pdu_session_id;
    uint32_t drb_id;
    nssai_t nssai;
} cucp_pdu_session_bearer_add_modify;

typedef struct _cucp_pdu_session_remove {
    uint64_t timestamp;
    uint64_t cucp_ue_index;
    uint32_t pdu_session_id;
} cucp_pdu_session_remove;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define du_ue_ctx_creation_init_default          {0, 0, 0, 0, 0, 0, 0}
#define du_ue_ctx_update_crnti_init_default      {0, 0, 0}
#define du_ue_ctx_deletion_init_default          {0, 0}
#define cucp_ue_ctx_creation_init_default        {0, 0, 0, false, 0, false, 0}
#define cucp_ue_ctx_update_init_default          {0, 0, 0, 0, 0}
#define cucp_ue_ctx_deletion_init_default        {0, 0}
#define e1ap_cucp_bearer_ctx_setup_init_default  {0, 0, 0}
#define e1ap_cuup_bearer_ctx_setup_init_default  {0, 0, 0, 0, 0}
#define e1ap_cuup_bearer_ctx_release_init_default {0, 0, 0, 0, 0}
#define nssai_t_init_default                     {0, 0}
#define cucp_pdu_session_bearer_add_modify_init_default {0, 0, 0, 0, nssai_t_init_default}
#define cucp_pdu_session_remove_init_default     {0, 0, 0}
#define du_ue_ctx_creation_init_zero             {0, 0, 0, 0, 0, 0, 0}
#define du_ue_ctx_update_crnti_init_zero         {0, 0, 0}
#define du_ue_ctx_deletion_init_zero             {0, 0}
#define cucp_ue_ctx_creation_init_zero           {0, 0, 0, false, 0, false, 0}
#define cucp_ue_ctx_update_init_zero             {0, 0, 0, 0, 0}
#define cucp_ue_ctx_deletion_init_zero           {0, 0}
#define e1ap_cucp_bearer_ctx_setup_init_zero     {0, 0, 0}
#define e1ap_cuup_bearer_ctx_setup_init_zero     {0, 0, 0, 0, 0}
#define e1ap_cuup_bearer_ctx_release_init_zero   {0, 0, 0, 0, 0}
#define nssai_t_init_zero                        {0, 0}
#define cucp_pdu_session_bearer_add_modify_init_zero {0, 0, 0, 0, nssai_t_init_zero}
#define cucp_pdu_session_remove_init_zero        {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define du_ue_ctx_creation_timestamp_tag         1
#define du_ue_ctx_creation_du_ue_index_tag       2
#define du_ue_ctx_creation_tac_tag               3
#define du_ue_ctx_creation_plmn_tag              4
#define du_ue_ctx_creation_nci_tag               5
#define du_ue_ctx_creation_pci_tag               6
#define du_ue_ctx_creation_crnti_tag             7
#define du_ue_ctx_update_crnti_timestamp_tag     1
#define du_ue_ctx_update_crnti_du_ue_index_tag   2
#define du_ue_ctx_update_crnti_crnti_tag         7
#define du_ue_ctx_deletion_timestamp_tag         1
#define du_ue_ctx_deletion_du_ue_index_tag       2
#define cucp_ue_ctx_creation_timestamp_tag       1
#define cucp_ue_ctx_creation_cucp_ue_index_tag   2
#define cucp_ue_ctx_creation_plmn_tag            3
#define cucp_ue_ctx_creation_pci_tag             4
#define cucp_ue_ctx_creation_crnti_tag           5
#define cucp_ue_ctx_update_timestamp_tag         1
#define cucp_ue_ctx_update_cucp_ue_index_tag     2
#define cucp_ue_ctx_update_plmn_tag              3
#define cucp_ue_ctx_update_pci_tag               4
#define cucp_ue_ctx_update_crnti_tag             5
#define cucp_ue_ctx_deletion_timestamp_tag       1
#define cucp_ue_ctx_deletion_cucp_ue_index_tag   2
#define e1ap_cucp_bearer_ctx_setup_timestamp_tag 1
#define e1ap_cucp_bearer_ctx_setup_cucp_ue_index_tag 2
#define e1ap_cucp_bearer_ctx_setup_cucp_ue_e1ap_id_tag 3
#define e1ap_cuup_bearer_ctx_setup_timestamp_tag 1
#define e1ap_cuup_bearer_ctx_setup_cuup_ue_index_tag 2
#define e1ap_cuup_bearer_ctx_setup_success_tag   3
#define e1ap_cuup_bearer_ctx_setup_cucp_ue_e1ap_id_tag 4
#define e1ap_cuup_bearer_ctx_setup_cuup_ue_e1ap_id_tag 5
#define e1ap_cuup_bearer_ctx_release_timestamp_tag 1
#define e1ap_cuup_bearer_ctx_release_cuup_ue_index_tag 2
#define e1ap_cuup_bearer_ctx_release_success_tag 3
#define e1ap_cuup_bearer_ctx_release_cucp_ue_e1ap_id_tag 4
#define e1ap_cuup_bearer_ctx_release_cuup_ue_e1ap_id_tag 5
#define nssai_t_sst_tag                          1
#define nssai_t_sd_tag                           2
#define cucp_pdu_session_bearer_add_modify_timestamp_tag 1
#define cucp_pdu_session_bearer_add_modify_cucp_ue_index_tag 2
#define cucp_pdu_session_bearer_add_modify_pdu_session_id_tag 3
#define cucp_pdu_session_bearer_add_modify_drb_id_tag 4
#define cucp_pdu_session_bearer_add_modify_nssai_tag 5
#define cucp_pdu_session_remove_timestamp_tag    1
#define cucp_pdu_session_remove_cucp_ue_index_tag 2
#define cucp_pdu_session_remove_pdu_session_id_tag 3

/* Struct field encoding specification for nanopb */
#define du_ue_ctx_creation_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT32,   du_ue_index,       2) \
X(a, STATIC,   REQUIRED, UINT32,   tac,               3) \
X(a, STATIC,   REQUIRED, UINT32,   plmn,              4) \
X(a, STATIC,   REQUIRED, UINT32,   nci,               5) \
X(a, STATIC,   REQUIRED, UINT32,   pci,               6) \
X(a, STATIC,   REQUIRED, UINT32,   crnti,             7)
#define du_ue_ctx_creation_CALLBACK NULL
#define du_ue_ctx_creation_DEFAULT NULL

#define du_ue_ctx_update_crnti_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT32,   du_ue_index,       2) \
X(a, STATIC,   REQUIRED, UINT32,   crnti,             7)
#define du_ue_ctx_update_crnti_CALLBACK NULL
#define du_ue_ctx_update_crnti_DEFAULT NULL

#define du_ue_ctx_deletion_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT32,   du_ue_index,       2)
#define du_ue_ctx_deletion_CALLBACK NULL
#define du_ue_ctx_deletion_DEFAULT NULL

#define cucp_ue_ctx_creation_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT32,   cucp_ue_index,     2) \
X(a, STATIC,   REQUIRED, UINT32,   plmn,              3) \
X(a, STATIC,   OPTIONAL, UINT32,   pci,               4) \
X(a, STATIC,   OPTIONAL, UINT32,   crnti,             5)
#define cucp_ue_ctx_creation_CALLBACK NULL
#define cucp_ue_ctx_creation_DEFAULT NULL

#define cucp_ue_ctx_update_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT32,   cucp_ue_index,     2) \
X(a, STATIC,   REQUIRED, UINT32,   plmn,              3) \
X(a, STATIC,   REQUIRED, UINT32,   pci,               4) \
X(a, STATIC,   REQUIRED, UINT32,   crnti,             5)
#define cucp_ue_ctx_update_CALLBACK NULL
#define cucp_ue_ctx_update_DEFAULT NULL

#define cucp_ue_ctx_deletion_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT32,   cucp_ue_index,     2)
#define cucp_ue_ctx_deletion_CALLBACK NULL
#define cucp_ue_ctx_deletion_DEFAULT NULL

#define e1ap_cucp_bearer_ctx_setup_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT32,   cucp_ue_index,     2) \
X(a, STATIC,   REQUIRED, UINT32,   cucp_ue_e1ap_id,   3)
#define e1ap_cucp_bearer_ctx_setup_CALLBACK NULL
#define e1ap_cucp_bearer_ctx_setup_DEFAULT NULL

#define e1ap_cuup_bearer_ctx_setup_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT32,   cuup_ue_index,     2) \
X(a, STATIC,   REQUIRED, BOOL,     success,           3) \
X(a, STATIC,   REQUIRED, UINT32,   cucp_ue_e1ap_id,   4) \
X(a, STATIC,   REQUIRED, UINT32,   cuup_ue_e1ap_id,   5)
#define e1ap_cuup_bearer_ctx_setup_CALLBACK NULL
#define e1ap_cuup_bearer_ctx_setup_DEFAULT NULL

#define e1ap_cuup_bearer_ctx_release_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT32,   cuup_ue_index,     2) \
X(a, STATIC,   REQUIRED, BOOL,     success,           3) \
X(a, STATIC,   REQUIRED, UINT32,   cucp_ue_e1ap_id,   4) \
X(a, STATIC,   REQUIRED, UINT32,   cuup_ue_e1ap_id,   5)
#define e1ap_cuup_bearer_ctx_release_CALLBACK NULL
#define e1ap_cuup_bearer_ctx_release_DEFAULT NULL

#define nssai_t_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   sst,               1) \
X(a, STATIC,   REQUIRED, UINT32,   sd,                2)
#define nssai_t_CALLBACK NULL
#define nssai_t_DEFAULT NULL

#define cucp_pdu_session_bearer_add_modify_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT64,   cucp_ue_index,     2) \
X(a, STATIC,   REQUIRED, UINT32,   pdu_session_id,    3) \
X(a, STATIC,   REQUIRED, UINT32,   drb_id,            4) \
X(a, STATIC,   REQUIRED, MESSAGE,  nssai,             5)
#define cucp_pdu_session_bearer_add_modify_CALLBACK NULL
#define cucp_pdu_session_bearer_add_modify_DEFAULT NULL
#define cucp_pdu_session_bearer_add_modify_nssai_MSGTYPE nssai_t

#define cucp_pdu_session_remove_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, UINT64,   cucp_ue_index,     2) \
X(a, STATIC,   REQUIRED, UINT32,   pdu_session_id,    3)
#define cucp_pdu_session_remove_CALLBACK NULL
#define cucp_pdu_session_remove_DEFAULT NULL

extern const pb_msgdesc_t du_ue_ctx_creation_msg;
extern const pb_msgdesc_t du_ue_ctx_update_crnti_msg;
extern const pb_msgdesc_t du_ue_ctx_deletion_msg;
extern const pb_msgdesc_t cucp_ue_ctx_creation_msg;
extern const pb_msgdesc_t cucp_ue_ctx_update_msg;
extern const pb_msgdesc_t cucp_ue_ctx_deletion_msg;
extern const pb_msgdesc_t e1ap_cucp_bearer_ctx_setup_msg;
extern const pb_msgdesc_t e1ap_cuup_bearer_ctx_setup_msg;
extern const pb_msgdesc_t e1ap_cuup_bearer_ctx_release_msg;
extern const pb_msgdesc_t nssai_t_msg;
extern const pb_msgdesc_t cucp_pdu_session_bearer_add_modify_msg;
extern const pb_msgdesc_t cucp_pdu_session_remove_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define du_ue_ctx_creation_fields &du_ue_ctx_creation_msg
#define du_ue_ctx_update_crnti_fields &du_ue_ctx_update_crnti_msg
#define du_ue_ctx_deletion_fields &du_ue_ctx_deletion_msg
#define cucp_ue_ctx_creation_fields &cucp_ue_ctx_creation_msg
#define cucp_ue_ctx_update_fields &cucp_ue_ctx_update_msg
#define cucp_ue_ctx_deletion_fields &cucp_ue_ctx_deletion_msg
#define e1ap_cucp_bearer_ctx_setup_fields &e1ap_cucp_bearer_ctx_setup_msg
#define e1ap_cuup_bearer_ctx_setup_fields &e1ap_cuup_bearer_ctx_setup_msg
#define e1ap_cuup_bearer_ctx_release_fields &e1ap_cuup_bearer_ctx_release_msg
#define nssai_t_fields &nssai_t_msg
#define cucp_pdu_session_bearer_add_modify_fields &cucp_pdu_session_bearer_add_modify_msg
#define cucp_pdu_session_remove_fields &cucp_pdu_session_remove_msg

/* Maximum encoded size of messages (where known) */
#define UE_CONTEXTS_PB_H_MAX_SIZE                cucp_pdu_session_bearer_add_modify_size
#define cucp_pdu_session_bearer_add_modify_size  48
#define cucp_pdu_session_remove_size             28
#define cucp_ue_ctx_creation_size                35
#define cucp_ue_ctx_deletion_size                17
#define cucp_ue_ctx_update_size                  35
#define du_ue_ctx_creation_size                  47
#define du_ue_ctx_deletion_size                  17
#define du_ue_ctx_update_crnti_size              23
#define e1ap_cucp_bearer_ctx_setup_size          23
#define e1ap_cuup_bearer_ctx_release_size        31
#define e1ap_cuup_bearer_ctx_setup_size          31
#define nssai_t_size                             12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
