/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_FAPI_GNB_CRC_STATS_PB_H_INCLUDED
#define PB_FAPI_GNB_CRC_STATS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _t_rnti_stats {
    uint32_t cell_id;
    uint32_t rnti;
    uint32_t l1_ta_min;
    uint32_t l1_ta_max;
    uint32_t l1_snr_min;
    uint32_t l1_snr_max;
    pb_size_t l1_crc_ta_hist_count;
    uint32_t l1_crc_ta_hist[8];
    pb_size_t l1_crc_snr_hist_count;
    uint32_t l1_crc_snr_hist[8];
} t_rnti_stats;

typedef struct _crc_stats {
    uint64_t timestamp;
    pb_size_t stats_count;
    t_rnti_stats stats[32];
} crc_stats;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define t_rnti_stats_init_default                {0, 0, 0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define crc_stats_init_default                   {0, 0, {t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default}}
#define t_rnti_stats_init_zero                   {0, 0, 0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define crc_stats_init_zero                      {0, 0, {t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define t_rnti_stats_cell_id_tag                 1
#define t_rnti_stats_rnti_tag                    2
#define t_rnti_stats_l1_ta_min_tag               3
#define t_rnti_stats_l1_ta_max_tag               4
#define t_rnti_stats_l1_snr_min_tag              5
#define t_rnti_stats_l1_snr_max_tag              6
#define t_rnti_stats_l1_crc_ta_hist_tag          7
#define t_rnti_stats_l1_crc_snr_hist_tag         8
#define crc_stats_timestamp_tag                  1
#define crc_stats_stats_tag                      2

/* Struct field encoding specification for nanopb */
#define t_rnti_stats_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   cell_id,           1) \
X(a, STATIC,   REQUIRED, UINT32,   rnti,              2) \
X(a, STATIC,   REQUIRED, UINT32,   l1_ta_min,         3) \
X(a, STATIC,   REQUIRED, UINT32,   l1_ta_max,         4) \
X(a, STATIC,   REQUIRED, UINT32,   l1_snr_min,        5) \
X(a, STATIC,   REQUIRED, UINT32,   l1_snr_max,        6) \
X(a, STATIC,   REPEATED, UINT32,   l1_crc_ta_hist,    7) \
X(a, STATIC,   REPEATED, UINT32,   l1_crc_snr_hist,   8)
#define t_rnti_stats_CALLBACK NULL
#define t_rnti_stats_DEFAULT NULL

#define crc_stats_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REPEATED, MESSAGE,  stats,             2)
#define crc_stats_CALLBACK NULL
#define crc_stats_DEFAULT NULL
#define crc_stats_stats_MSGTYPE t_rnti_stats

extern const pb_msgdesc_t t_rnti_stats_msg;
extern const pb_msgdesc_t crc_stats_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define t_rnti_stats_fields &t_rnti_stats_msg
#define crc_stats_fields &crc_stats_msg

/* Maximum encoded size of messages (where known) */
#define FAPI_GNB_CRC_STATS_PB_H_MAX_SIZE         crc_stats_size
#define crc_stats_size                           4331
#define t_rnti_stats_size                        132

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
