/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MAC_SCHED_BSR_STATS_CUSTOM_PB_H_INCLUDED
#define PB_MAC_SCHED_BSR_STATS_CUSTOM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _t_bsr_stats_custom {
    uint32_t du_ue_index;
    uint32_t cnt; /* BSR events in reporting window */
    uint64_t total_bytes; /* sum of bytes in reporting window */
    uint64_t max_bytes; /* max bytes seen in reporting window */
    /* Sliding window (last 16 BSR events, stored in KB = bytes >> 10) */
    int32_t bsr_sliding_avg_kb; /* sliding window average (KB) */
    uint32_t bsr_sliding_cnt; /* samples in window (≤ 16) */
} t_bsr_stats_custom;

typedef struct _bsr_stats_custom {
    uint64_t timestamp;
    pb_size_t stats_count;
    t_bsr_stats_custom stats[32];
} bsr_stats_custom;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define t_bsr_stats_custom_init_default          {0, 0, 0, 0, 0, 0}
#define bsr_stats_custom_init_default            {0, 0, {t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default, t_bsr_stats_custom_init_default}}
#define t_bsr_stats_custom_init_zero             {0, 0, 0, 0, 0, 0}
#define bsr_stats_custom_init_zero               {0, 0, {t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero, t_bsr_stats_custom_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define t_bsr_stats_custom_du_ue_index_tag       1
#define t_bsr_stats_custom_cnt_tag               2
#define t_bsr_stats_custom_total_bytes_tag       3
#define t_bsr_stats_custom_max_bytes_tag         4
#define t_bsr_stats_custom_bsr_sliding_avg_kb_tag 5
#define t_bsr_stats_custom_bsr_sliding_cnt_tag   6
#define bsr_stats_custom_timestamp_tag           1
#define bsr_stats_custom_stats_tag               2

/* Struct field encoding specification for nanopb */
#define t_bsr_stats_custom_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   du_ue_index,       1) \
X(a, STATIC,   REQUIRED, UINT32,   cnt,               2) \
X(a, STATIC,   REQUIRED, UINT64,   total_bytes,       3) \
X(a, STATIC,   REQUIRED, UINT64,   max_bytes,         4) \
X(a, STATIC,   REQUIRED, INT32,    bsr_sliding_avg_kb,   5) \
X(a, STATIC,   REQUIRED, UINT32,   bsr_sliding_cnt,   6)
#define t_bsr_stats_custom_CALLBACK NULL
#define t_bsr_stats_custom_DEFAULT NULL

#define bsr_stats_custom_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REPEATED, MESSAGE,  stats,             2)
#define bsr_stats_custom_CALLBACK NULL
#define bsr_stats_custom_DEFAULT NULL
#define bsr_stats_custom_stats_MSGTYPE t_bsr_stats_custom

extern const pb_msgdesc_t t_bsr_stats_custom_msg;
extern const pb_msgdesc_t bsr_stats_custom_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define t_bsr_stats_custom_fields &t_bsr_stats_custom_msg
#define bsr_stats_custom_fields &bsr_stats_custom_msg

/* Maximum encoded size of messages (where known) */
#define MAC_SCHED_BSR_STATS_CUSTOM_PB_H_MAX_SIZE bsr_stats_custom_size
#define bsr_stats_custom_size                    1707
#define t_bsr_stats_custom_size                  51

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
