/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MAC_SCHED_CRC_STATS_PB_H_INCLUDED
#define PB_MAC_SCHED_CRC_STATS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _t_crc_stats {
    uint32_t du_ue_index;
    uint32_t cons_max;
    uint32_t succ_tx;
    uint32_t cnt_tx;
    uint32_t retx_hist[16];
    uint32_t harq_failure;
    int32_t min_sinr;
    int32_t min_rsrp;
    int32_t max_sinr;
    int32_t max_rsrp;
    int32_t sum_sinr;
    int32_t sum_rsrp;
    uint32_t cnt_sinr;
    uint32_t cnt_rsrp;
} t_crc_stats;

typedef struct _crc_stats {
    uint64_t timestamp;
    pb_size_t stats_count;
    t_crc_stats stats[32];
} crc_stats;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define t_crc_stats_init_default                 {0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define crc_stats_init_default                   {0, 0, {t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default, t_crc_stats_init_default}}
#define t_crc_stats_init_zero                    {0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define crc_stats_init_zero                      {0, 0, {t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero, t_crc_stats_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define t_crc_stats_du_ue_index_tag              1
#define t_crc_stats_cons_max_tag                 2
#define t_crc_stats_succ_tx_tag                  3
#define t_crc_stats_cnt_tx_tag                   4
#define t_crc_stats_retx_hist_tag                5
#define t_crc_stats_harq_failure_tag             6
#define t_crc_stats_min_sinr_tag                 7
#define t_crc_stats_min_rsrp_tag                 8
#define t_crc_stats_max_sinr_tag                 9
#define t_crc_stats_max_rsrp_tag                 10
#define t_crc_stats_sum_sinr_tag                 11
#define t_crc_stats_sum_rsrp_tag                 12
#define t_crc_stats_cnt_sinr_tag                 13
#define t_crc_stats_cnt_rsrp_tag                 14
#define crc_stats_timestamp_tag                  1
#define crc_stats_stats_tag                      2

/* Struct field encoding specification for nanopb */
#define t_crc_stats_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   du_ue_index,       1) \
X(a, STATIC,   REQUIRED, UINT32,   cons_max,          2) \
X(a, STATIC,   REQUIRED, UINT32,   succ_tx,           3) \
X(a, STATIC,   REQUIRED, UINT32,   cnt_tx,            4) \
X(a, STATIC,   FIXARRAY, UINT32,   retx_hist,         5) \
X(a, STATIC,   REQUIRED, UINT32,   harq_failure,      6) \
X(a, STATIC,   REQUIRED, INT32,    min_sinr,          7) \
X(a, STATIC,   REQUIRED, INT32,    min_rsrp,          8) \
X(a, STATIC,   REQUIRED, INT32,    max_sinr,          9) \
X(a, STATIC,   REQUIRED, INT32,    max_rsrp,         10) \
X(a, STATIC,   REQUIRED, INT32,    sum_sinr,         11) \
X(a, STATIC,   REQUIRED, INT32,    sum_rsrp,         12) \
X(a, STATIC,   REQUIRED, UINT32,   cnt_sinr,         13) \
X(a, STATIC,   REQUIRED, UINT32,   cnt_rsrp,         14)
#define t_crc_stats_CALLBACK NULL
#define t_crc_stats_DEFAULT NULL

#define crc_stats_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REPEATED, MESSAGE,  stats,             2)
#define crc_stats_CALLBACK NULL
#define crc_stats_DEFAULT NULL
#define crc_stats_stats_MSGTYPE t_crc_stats

extern const pb_msgdesc_t t_crc_stats_msg;
extern const pb_msgdesc_t crc_stats_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define t_crc_stats_fields &t_crc_stats_msg
#define crc_stats_fields &crc_stats_msg

/* Maximum encoded size of messages (where known) */
#define MAC_SCHED_CRC_STATS_PB_H_MAX_SIZE        crc_stats_size
#define crc_stats_size                           6635
#define t_crc_stats_size                         204

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
