/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MAC_SCHED_BSR_STATS_PB_H_INCLUDED
#define PB_MAC_SCHED_BSR_STATS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _t_bsr_stats {
    uint32_t du_ue_index;
    uint32_t cnt;
    uint64_t bytes;
} t_bsr_stats;

typedef struct _bsr_stats {
    uint64_t timestamp;
    pb_size_t stats_count;
    t_bsr_stats stats[32];
} bsr_stats;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define t_bsr_stats_init_default                 {0, 0, 0}
#define bsr_stats_init_default                   {0, 0, {t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default, t_bsr_stats_init_default}}
#define t_bsr_stats_init_zero                    {0, 0, 0}
#define bsr_stats_init_zero                      {0, 0, {t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero, t_bsr_stats_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define t_bsr_stats_du_ue_index_tag              1
#define t_bsr_stats_cnt_tag                      2
#define t_bsr_stats_bytes_tag                    3
#define bsr_stats_timestamp_tag                  1
#define bsr_stats_stats_tag                      2

/* Struct field encoding specification for nanopb */
#define t_bsr_stats_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   du_ue_index,       1) \
X(a, STATIC,   REQUIRED, UINT32,   cnt,               2) \
X(a, STATIC,   REQUIRED, UINT64,   bytes,             3)
#define t_bsr_stats_CALLBACK NULL
#define t_bsr_stats_DEFAULT NULL

#define bsr_stats_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REPEATED, MESSAGE,  stats,             2)
#define bsr_stats_CALLBACK NULL
#define bsr_stats_DEFAULT NULL
#define bsr_stats_stats_MSGTYPE t_bsr_stats

extern const pb_msgdesc_t t_bsr_stats_msg;
extern const pb_msgdesc_t bsr_stats_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define t_bsr_stats_fields &t_bsr_stats_msg
#define bsr_stats_fields &bsr_stats_msg

/* Maximum encoded size of messages (where known) */
#define MAC_SCHED_BSR_STATS_PB_H_MAX_SIZE        bsr_stats_size
#define bsr_stats_size                           811
#define t_bsr_stats_size                         23

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
