/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MAC_SCHED_UCI_STATS_PB_H_INCLUDED
#define PB_MAC_SCHED_UCI_STATS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _uci_stat_item_t {
    uint32_t count;
    uint32_t total;
    uint32_t min;
    uint32_t max;
} uci_stat_item_t;

typedef struct _uci_uint64_stats_item {
    uint32_t count;
    uint64_t total;
    uint64_t min;
    uint64_t max;
} uci_uint64_stats_item;

typedef struct _csi_stats_item {
    bool has_ri;
    uci_stat_item_t ri;
    bool has_cqi;
    uci_stat_item_t cqi;
} csi_stats_item;

typedef struct _t_uci_stats {
    uint32_t du_ue_index;
    uint32_t sr_detected;
    bool has_time_advance_offset;
    uci_uint64_stats_item time_advance_offset;
    bool has_csi;
    csi_stats_item csi;
} t_uci_stats;

typedef struct _uci_stats {
    uint64_t timestamp;
    pb_size_t stats_count;
    t_uci_stats stats[32];
} uci_stats;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define uci_stat_item_t_init_default             {0, 0, 0, 0}
#define uci_uint64_stats_item_init_default       {0, 0, 0, 0}
#define csi_stats_item_init_default              {false, uci_stat_item_t_init_default, false, uci_stat_item_t_init_default}
#define t_uci_stats_init_default                 {0, 0, false, uci_uint64_stats_item_init_default, false, csi_stats_item_init_default}
#define uci_stats_init_default                   {0, 0, {t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default, t_uci_stats_init_default}}
#define uci_stat_item_t_init_zero                {0, 0, 0, 0}
#define uci_uint64_stats_item_init_zero          {0, 0, 0, 0}
#define csi_stats_item_init_zero                 {false, uci_stat_item_t_init_zero, false, uci_stat_item_t_init_zero}
#define t_uci_stats_init_zero                    {0, 0, false, uci_uint64_stats_item_init_zero, false, csi_stats_item_init_zero}
#define uci_stats_init_zero                      {0, 0, {t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero, t_uci_stats_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define uci_stat_item_t_count_tag                1
#define uci_stat_item_t_total_tag                2
#define uci_stat_item_t_min_tag                  3
#define uci_stat_item_t_max_tag                  4
#define uci_uint64_stats_item_count_tag          1
#define uci_uint64_stats_item_total_tag          2
#define uci_uint64_stats_item_min_tag            3
#define uci_uint64_stats_item_max_tag            4
#define csi_stats_item_ri_tag                    1
#define csi_stats_item_cqi_tag                   2
#define t_uci_stats_du_ue_index_tag              1
#define t_uci_stats_sr_detected_tag              2
#define t_uci_stats_time_advance_offset_tag      3
#define t_uci_stats_csi_tag                      4
#define uci_stats_timestamp_tag                  1
#define uci_stats_stats_tag                      2

/* Struct field encoding specification for nanopb */
#define uci_stat_item_t_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   count,             1) \
X(a, STATIC,   REQUIRED, UINT32,   total,             2) \
X(a, STATIC,   REQUIRED, UINT32,   min,               3) \
X(a, STATIC,   REQUIRED, UINT32,   max,               4)
#define uci_stat_item_t_CALLBACK NULL
#define uci_stat_item_t_DEFAULT NULL

#define uci_uint64_stats_item_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   count,             1) \
X(a, STATIC,   REQUIRED, UINT64,   total,             2) \
X(a, STATIC,   REQUIRED, UINT64,   min,               3) \
X(a, STATIC,   REQUIRED, UINT64,   max,               4)
#define uci_uint64_stats_item_CALLBACK NULL
#define uci_uint64_stats_item_DEFAULT NULL

#define csi_stats_item_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ri,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cqi,               2)
#define csi_stats_item_CALLBACK NULL
#define csi_stats_item_DEFAULT NULL
#define csi_stats_item_ri_MSGTYPE uci_stat_item_t
#define csi_stats_item_cqi_MSGTYPE uci_stat_item_t

#define t_uci_stats_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   du_ue_index,       1) \
X(a, STATIC,   REQUIRED, UINT32,   sr_detected,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  time_advance_offset,   3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  csi,               4)
#define t_uci_stats_CALLBACK NULL
#define t_uci_stats_DEFAULT NULL
#define t_uci_stats_time_advance_offset_MSGTYPE uci_uint64_stats_item
#define t_uci_stats_csi_MSGTYPE csi_stats_item

#define uci_stats_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REPEATED, MESSAGE,  stats,             2)
#define uci_stats_CALLBACK NULL
#define uci_stats_DEFAULT NULL
#define uci_stats_stats_MSGTYPE t_uci_stats

extern const pb_msgdesc_t uci_stat_item_t_msg;
extern const pb_msgdesc_t uci_uint64_stats_item_msg;
extern const pb_msgdesc_t csi_stats_item_msg;
extern const pb_msgdesc_t t_uci_stats_msg;
extern const pb_msgdesc_t uci_stats_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define uci_stat_item_t_fields &uci_stat_item_t_msg
#define uci_uint64_stats_item_fields &uci_uint64_stats_item_msg
#define csi_stats_item_fields &csi_stats_item_msg
#define t_uci_stats_fields &t_uci_stats_msg
#define uci_stats_fields &uci_stats_msg

/* Maximum encoded size of messages (where known) */
#define MAC_SCHED_UCI_STATS_PB_H_MAX_SIZE        uci_stats_size
#define csi_stats_item_size                      52
#define t_uci_stats_size                         107
#define uci_stat_item_t_size                     24
#define uci_stats_size                           3499
#define uci_uint64_stats_item_size               39

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
