/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MAC_SCHED_HARQ_STATS_PB_H_INCLUDED
#define PB_MAC_SCHED_HARQ_STATS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _t_harq_stat_item {
    uint32_t count;
    uint64_t total;
    uint32_t min;
    uint32_t max;
} t_harq_stat_item;

typedef struct _t_harq_stat_traffic_item {
    uint32_t count;
    uint64_t total;
} t_harq_stat_traffic_item;

typedef struct _t_harq_type_stats {
    uint32_t count;
    t_harq_stat_traffic_item tbs_bytes;
    bool has_cqi;
    t_harq_stat_item cqi;
} t_harq_type_stats;

typedef struct _t_harq_stats {
    uint32_t cell_id;
    uint32_t rnti;
    uint32_t du_ue_index;
    uint32_t max_nof_harq_retxs;
    uint32_t mcs_table;
    t_harq_stat_item cons_retx;
    t_harq_stat_item mcs;
    t_harq_type_stats perHarqTypeStats[3];
} t_harq_stats;

typedef struct _harq_stats {
    uint64_t timestamp;
    pb_size_t stats_count;
    t_harq_stats stats[32];
} harq_stats;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define t_harq_stat_item_init_default            {0, 0, 0, 0}
#define t_harq_stat_traffic_item_init_default    {0, 0}
#define t_harq_type_stats_init_default           {0, t_harq_stat_traffic_item_init_default, false, t_harq_stat_item_init_default}
#define t_harq_stats_init_default                {0, 0, 0, 0, 0, t_harq_stat_item_init_default, t_harq_stat_item_init_default, {t_harq_type_stats_init_default, t_harq_type_stats_init_default, t_harq_type_stats_init_default}}
#define harq_stats_init_default                  {0, 0, {t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default, t_harq_stats_init_default}}
#define t_harq_stat_item_init_zero               {0, 0, 0, 0}
#define t_harq_stat_traffic_item_init_zero       {0, 0}
#define t_harq_type_stats_init_zero              {0, t_harq_stat_traffic_item_init_zero, false, t_harq_stat_item_init_zero}
#define t_harq_stats_init_zero                   {0, 0, 0, 0, 0, t_harq_stat_item_init_zero, t_harq_stat_item_init_zero, {t_harq_type_stats_init_zero, t_harq_type_stats_init_zero, t_harq_type_stats_init_zero}}
#define harq_stats_init_zero                     {0, 0, {t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero, t_harq_stats_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define t_harq_stat_item_count_tag               1
#define t_harq_stat_item_total_tag               2
#define t_harq_stat_item_min_tag                 3
#define t_harq_stat_item_max_tag                 4
#define t_harq_stat_traffic_item_count_tag       1
#define t_harq_stat_traffic_item_total_tag       2
#define t_harq_type_stats_count_tag              1
#define t_harq_type_stats_tbs_bytes_tag          2
#define t_harq_type_stats_cqi_tag                3
#define t_harq_stats_cell_id_tag                 1
#define t_harq_stats_rnti_tag                    2
#define t_harq_stats_du_ue_index_tag             3
#define t_harq_stats_max_nof_harq_retxs_tag      4
#define t_harq_stats_mcs_table_tag               5
#define t_harq_stats_cons_retx_tag               6
#define t_harq_stats_mcs_tag                     7
#define t_harq_stats_perHarqTypeStats_tag        8
#define harq_stats_timestamp_tag                 1
#define harq_stats_stats_tag                     2

/* Struct field encoding specification for nanopb */
#define t_harq_stat_item_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   count,             1) \
X(a, STATIC,   REQUIRED, UINT64,   total,             2) \
X(a, STATIC,   REQUIRED, UINT32,   min,               3) \
X(a, STATIC,   REQUIRED, UINT32,   max,               4)
#define t_harq_stat_item_CALLBACK NULL
#define t_harq_stat_item_DEFAULT NULL

#define t_harq_stat_traffic_item_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   count,             1) \
X(a, STATIC,   REQUIRED, UINT64,   total,             2)
#define t_harq_stat_traffic_item_CALLBACK NULL
#define t_harq_stat_traffic_item_DEFAULT NULL

#define t_harq_type_stats_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   count,             1) \
X(a, STATIC,   REQUIRED, MESSAGE,  tbs_bytes,         2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cqi,               3)
#define t_harq_type_stats_CALLBACK NULL
#define t_harq_type_stats_DEFAULT NULL
#define t_harq_type_stats_tbs_bytes_MSGTYPE t_harq_stat_traffic_item
#define t_harq_type_stats_cqi_MSGTYPE t_harq_stat_item

#define t_harq_stats_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   cell_id,           1) \
X(a, STATIC,   REQUIRED, UINT32,   rnti,              2) \
X(a, STATIC,   REQUIRED, UINT32,   du_ue_index,       3) \
X(a, STATIC,   REQUIRED, UINT32,   max_nof_harq_retxs,   4) \
X(a, STATIC,   REQUIRED, UINT32,   mcs_table,         5) \
X(a, STATIC,   REQUIRED, MESSAGE,  cons_retx,         6) \
X(a, STATIC,   REQUIRED, MESSAGE,  mcs,               7) \
X(a, STATIC,   FIXARRAY, MESSAGE,  perHarqTypeStats,   8)
#define t_harq_stats_CALLBACK NULL
#define t_harq_stats_DEFAULT NULL
#define t_harq_stats_cons_retx_MSGTYPE t_harq_stat_item
#define t_harq_stats_mcs_MSGTYPE t_harq_stat_item
#define t_harq_stats_perHarqTypeStats_MSGTYPE t_harq_type_stats

#define harq_stats_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REPEATED, MESSAGE,  stats,             2)
#define harq_stats_CALLBACK NULL
#define harq_stats_DEFAULT NULL
#define harq_stats_stats_MSGTYPE t_harq_stats

extern const pb_msgdesc_t t_harq_stat_item_msg;
extern const pb_msgdesc_t t_harq_stat_traffic_item_msg;
extern const pb_msgdesc_t t_harq_type_stats_msg;
extern const pb_msgdesc_t t_harq_stats_msg;
extern const pb_msgdesc_t harq_stats_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define t_harq_stat_item_fields &t_harq_stat_item_msg
#define t_harq_stat_traffic_item_fields &t_harq_stat_traffic_item_msg
#define t_harq_type_stats_fields &t_harq_type_stats_msg
#define t_harq_stats_fields &t_harq_stats_msg
#define harq_stats_fields &harq_stats_msg

/* Maximum encoded size of messages (where known) */
#define MAC_SCHED_HARQ_STATS_PB_H_MAX_SIZE       harq_stats_size
#define harq_stats_size                          8619
#define t_harq_stat_item_size                    29
#define t_harq_stat_traffic_item_size            17
#define t_harq_stats_size                        266
#define t_harq_type_stats_size                   56

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
