/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MAC_SCHED_UL_HARQ_STATS_CUSTOM_PB_H_INCLUDED
#define PB_MAC_SCHED_UL_HARQ_STATS_CUSTOM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _t_ul_harq_stats_custom {
    uint32_t du_ue_index;
    uint32_t mcs_count; /* number of HARQ events in window */
    uint32_t mcs_sum; /* sum of MCS values in window */
    uint32_t mcs_min; /* min MCS in window */
    uint32_t mcs_max; /* max MCS in window */
    /* Sliding window fields (last 16 HARQ MCS values) */
    int32_t mcs_sliding_avg; /* sliding window average of MCS */
    uint32_t mcs_sliding_cnt; /* samples currently in window */
    int32_t mcs_variance; /* variance of MCS: E[X^2] - E[X]^2 */
    /* HARQ retransmission count */
    uint32_t cons_retx_max; /* max consecutive retransmissions in window */
} t_ul_harq_stats_custom;

typedef struct _ul_harq_stats_custom {
    uint64_t timestamp;
    pb_size_t stats_count;
    t_ul_harq_stats_custom stats[32];
} ul_harq_stats_custom;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define t_ul_harq_stats_custom_init_default      {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ul_harq_stats_custom_init_default        {0, 0, {t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default, t_ul_harq_stats_custom_init_default}}
#define t_ul_harq_stats_custom_init_zero         {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define ul_harq_stats_custom_init_zero           {0, 0, {t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero, t_ul_harq_stats_custom_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define t_ul_harq_stats_custom_du_ue_index_tag   1
#define t_ul_harq_stats_custom_mcs_count_tag     2
#define t_ul_harq_stats_custom_mcs_sum_tag       3
#define t_ul_harq_stats_custom_mcs_min_tag       4
#define t_ul_harq_stats_custom_mcs_max_tag       5
#define t_ul_harq_stats_custom_mcs_sliding_avg_tag 6
#define t_ul_harq_stats_custom_mcs_sliding_cnt_tag 7
#define t_ul_harq_stats_custom_mcs_variance_tag  8
#define t_ul_harq_stats_custom_cons_retx_max_tag 9
#define ul_harq_stats_custom_timestamp_tag       1
#define ul_harq_stats_custom_stats_tag           2

/* Struct field encoding specification for nanopb */
#define t_ul_harq_stats_custom_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   du_ue_index,       1) \
X(a, STATIC,   REQUIRED, UINT32,   mcs_count,         2) \
X(a, STATIC,   REQUIRED, UINT32,   mcs_sum,           3) \
X(a, STATIC,   REQUIRED, UINT32,   mcs_min,           4) \
X(a, STATIC,   REQUIRED, UINT32,   mcs_max,           5) \
X(a, STATIC,   REQUIRED, INT32,    mcs_sliding_avg,   6) \
X(a, STATIC,   REQUIRED, UINT32,   mcs_sliding_cnt,   7) \
X(a, STATIC,   REQUIRED, INT32,    mcs_variance,      8) \
X(a, STATIC,   REQUIRED, UINT32,   cons_retx_max,     9)
#define t_ul_harq_stats_custom_CALLBACK NULL
#define t_ul_harq_stats_custom_DEFAULT NULL

#define ul_harq_stats_custom_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REPEATED, MESSAGE,  stats,             2)
#define ul_harq_stats_custom_CALLBACK NULL
#define ul_harq_stats_custom_DEFAULT NULL
#define ul_harq_stats_custom_stats_MSGTYPE t_ul_harq_stats_custom

extern const pb_msgdesc_t t_ul_harq_stats_custom_msg;
extern const pb_msgdesc_t ul_harq_stats_custom_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define t_ul_harq_stats_custom_fields &t_ul_harq_stats_custom_msg
#define ul_harq_stats_custom_fields &ul_harq_stats_custom_msg

/* Maximum encoded size of messages (where known) */
#define MAC_SCHED_UL_HARQ_STATS_CUSTOM_PB_H_MAX_SIZE ul_harq_stats_custom_size
#define t_ul_harq_stats_custom_size              64
#define ul_harq_stats_custom_size                2123

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
