/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_FAPI_GNB_UL_CONFIG_STATS_PB_H_INCLUDED
#define PB_FAPI_GNB_UL_CONFIG_STATS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _t_rnti_stats {
    uint32_t cell_id;
    uint32_t rnti;
    uint32_t l1_cnt;
    uint32_t l1_ulc_tx;
    uint32_t l1_prb_min;
    uint32_t l1_prb_max;
    uint32_t l1_prb_avg;
    uint32_t l1_tbs_min;
    uint32_t l1_tbs_max;
    uint32_t l1_tbs_avg;
    uint32_t l1_mcs_min;
    uint32_t l1_mcs_max;
    uint32_t l1_mcs_avg;
    uint32_t l1_ant_avg;
    pb_size_t l1_ulc_prb_hist_count;
    uint32_t l1_ulc_prb_hist[8];
    pb_size_t l1_ulc_mcs_hist_count;
    uint32_t l1_ulc_mcs_hist[8];
    pb_size_t l1_ulc_tbs_hist_count;
    uint32_t l1_ulc_tbs_hist[8];
    pb_size_t l1_ulc_ant_hist_count;
    uint32_t l1_ulc_ant_hist[4];
} t_rnti_stats;

typedef struct _ul_config_stats {
    uint64_t timestamp;
    pb_size_t stats_count;
    t_rnti_stats stats[32];
} ul_config_stats;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define t_rnti_stats_init_default                {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0}}
#define ul_config_stats_init_default             {0, 0, {t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default, t_rnti_stats_init_default}}
#define t_rnti_stats_init_zero                   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0}}
#define ul_config_stats_init_zero                {0, 0, {t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero, t_rnti_stats_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define t_rnti_stats_cell_id_tag                 1
#define t_rnti_stats_rnti_tag                    2
#define t_rnti_stats_l1_cnt_tag                  3
#define t_rnti_stats_l1_ulc_tx_tag               4
#define t_rnti_stats_l1_prb_min_tag              5
#define t_rnti_stats_l1_prb_max_tag              6
#define t_rnti_stats_l1_prb_avg_tag              7
#define t_rnti_stats_l1_tbs_min_tag              8
#define t_rnti_stats_l1_tbs_max_tag              9
#define t_rnti_stats_l1_tbs_avg_tag              10
#define t_rnti_stats_l1_mcs_min_tag              11
#define t_rnti_stats_l1_mcs_max_tag              12
#define t_rnti_stats_l1_mcs_avg_tag              13
#define t_rnti_stats_l1_ant_avg_tag              14
#define t_rnti_stats_l1_ulc_prb_hist_tag         15
#define t_rnti_stats_l1_ulc_mcs_hist_tag         16
#define t_rnti_stats_l1_ulc_tbs_hist_tag         17
#define t_rnti_stats_l1_ulc_ant_hist_tag         18
#define ul_config_stats_timestamp_tag            1
#define ul_config_stats_stats_tag                2

/* Struct field encoding specification for nanopb */
#define t_rnti_stats_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   cell_id,           1) \
X(a, STATIC,   REQUIRED, UINT32,   rnti,              2) \
X(a, STATIC,   REQUIRED, UINT32,   l1_cnt,            3) \
X(a, STATIC,   REQUIRED, UINT32,   l1_ulc_tx,         4) \
X(a, STATIC,   REQUIRED, UINT32,   l1_prb_min,        5) \
X(a, STATIC,   REQUIRED, UINT32,   l1_prb_max,        6) \
X(a, STATIC,   REQUIRED, UINT32,   l1_prb_avg,        7) \
X(a, STATIC,   REQUIRED, UINT32,   l1_tbs_min,        8) \
X(a, STATIC,   REQUIRED, UINT32,   l1_tbs_max,        9) \
X(a, STATIC,   REQUIRED, UINT32,   l1_tbs_avg,       10) \
X(a, STATIC,   REQUIRED, UINT32,   l1_mcs_min,       11) \
X(a, STATIC,   REQUIRED, UINT32,   l1_mcs_max,       12) \
X(a, STATIC,   REQUIRED, UINT32,   l1_mcs_avg,       13) \
X(a, STATIC,   REQUIRED, UINT32,   l1_ant_avg,       14) \
X(a, STATIC,   REPEATED, UINT32,   l1_ulc_prb_hist,  15) \
X(a, STATIC,   REPEATED, UINT32,   l1_ulc_mcs_hist,  16) \
X(a, STATIC,   REPEATED, UINT32,   l1_ulc_tbs_hist,  17) \
X(a, STATIC,   REPEATED, UINT32,   l1_ulc_ant_hist,  18)
#define t_rnti_stats_CALLBACK NULL
#define t_rnti_stats_DEFAULT NULL

#define ul_config_stats_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REPEATED, MESSAGE,  stats,             2)
#define ul_config_stats_CALLBACK NULL
#define ul_config_stats_DEFAULT NULL
#define ul_config_stats_stats_MSGTYPE t_rnti_stats

extern const pb_msgdesc_t t_rnti_stats_msg;
extern const pb_msgdesc_t ul_config_stats_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define t_rnti_stats_fields &t_rnti_stats_msg
#define ul_config_stats_fields &ul_config_stats_msg

/* Maximum encoded size of messages (where known) */
#define FAPI_GNB_UL_CONFIG_STATS_PB_H_MAX_SIZE   ul_config_stats_size
#define t_rnti_stats_size                        272
#define ul_config_stats_size                     8811

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
