/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_NGAP_PB_H_INCLUDED
#define PB_NGAP_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ngap_ctx {
    uint32_t cucp_ue_index;
    bool has_ran_ue_id;
    uint32_t ran_ue_id;
    bool has_amf_ue_id;
    uint32_t amf_ue_id;
} ngap_ctx;

typedef struct _ngap_procedure_started {
    uint64_t timestamp;
    ngap_ctx ue_ctx;
    uint32_t procedure;
} ngap_procedure_started;

typedef struct _ngap_procedure_completed {
    uint64_t timestamp;
    ngap_ctx ue_ctx;
    uint32_t procedure;
    uint32_t success;
} ngap_procedure_completed;

typedef struct _ngap_reset {
    uint64_t timestamp;
    bool has_ue_ctx;
    ngap_ctx ue_ctx;
} ngap_reset;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ngap_ctx_init_default                    {0, false, 0, false, 0}
#define ngap_procedure_started_init_default      {0, ngap_ctx_init_default, 0}
#define ngap_procedure_completed_init_default    {0, ngap_ctx_init_default, 0, 0}
#define ngap_reset_init_default                  {0, false, ngap_ctx_init_default}
#define ngap_ctx_init_zero                       {0, false, 0, false, 0}
#define ngap_procedure_started_init_zero         {0, ngap_ctx_init_zero, 0}
#define ngap_procedure_completed_init_zero       {0, ngap_ctx_init_zero, 0, 0}
#define ngap_reset_init_zero                     {0, false, ngap_ctx_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define ngap_ctx_cucp_ue_index_tag               1
#define ngap_ctx_ran_ue_id_tag                   2
#define ngap_ctx_amf_ue_id_tag                   3
#define ngap_procedure_started_timestamp_tag     1
#define ngap_procedure_started_ue_ctx_tag        2
#define ngap_procedure_started_procedure_tag     3
#define ngap_procedure_completed_timestamp_tag   1
#define ngap_procedure_completed_ue_ctx_tag      2
#define ngap_procedure_completed_procedure_tag   3
#define ngap_procedure_completed_success_tag     4
#define ngap_reset_timestamp_tag                 1
#define ngap_reset_ue_ctx_tag                    2

/* Struct field encoding specification for nanopb */
#define ngap_ctx_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   cucp_ue_index,     1) \
X(a, STATIC,   OPTIONAL, UINT32,   ran_ue_id,         2) \
X(a, STATIC,   OPTIONAL, UINT32,   amf_ue_id,         3)
#define ngap_ctx_CALLBACK NULL
#define ngap_ctx_DEFAULT NULL

#define ngap_procedure_started_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, MESSAGE,  ue_ctx,            2) \
X(a, STATIC,   REQUIRED, UINT32,   procedure,         3)
#define ngap_procedure_started_CALLBACK NULL
#define ngap_procedure_started_DEFAULT NULL
#define ngap_procedure_started_ue_ctx_MSGTYPE ngap_ctx

#define ngap_procedure_completed_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   REQUIRED, MESSAGE,  ue_ctx,            2) \
X(a, STATIC,   REQUIRED, UINT32,   procedure,         3) \
X(a, STATIC,   REQUIRED, UINT32,   success,           4)
#define ngap_procedure_completed_CALLBACK NULL
#define ngap_procedure_completed_DEFAULT NULL
#define ngap_procedure_completed_ue_ctx_MSGTYPE ngap_ctx

#define ngap_reset_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   timestamp,         1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ue_ctx,            2)
#define ngap_reset_CALLBACK NULL
#define ngap_reset_DEFAULT NULL
#define ngap_reset_ue_ctx_MSGTYPE ngap_ctx

extern const pb_msgdesc_t ngap_ctx_msg;
extern const pb_msgdesc_t ngap_procedure_started_msg;
extern const pb_msgdesc_t ngap_procedure_completed_msg;
extern const pb_msgdesc_t ngap_reset_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ngap_ctx_fields &ngap_ctx_msg
#define ngap_procedure_started_fields &ngap_procedure_started_msg
#define ngap_procedure_completed_fields &ngap_procedure_completed_msg
#define ngap_reset_fields &ngap_reset_msg

/* Maximum encoded size of messages (where known) */
#define NGAP_PB_H_MAX_SIZE                       ngap_procedure_completed_size
#define ngap_ctx_size                            18
#define ngap_procedure_completed_size            43
#define ngap_procedure_started_size              37
#define ngap_reset_size                          31

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
